// Generated by CoffeeScript 1.10.0
(function() {
  var App;

  App = {};

  var isDrawing = false;


  /*
  	Init
   */

  App.init = function() {
    App.canvas = document.createElement('canvas');
    App.canvas.height = window.innerHeight;
    App.canvas.width = window.innerWidth;
    document.getElementsByTagName('article')[0].appendChild(App.canvas);
    App.ctx = App.canvas.getContext("2d");
    App.ctx.fillStyle = "solid";
    App.ctx.strokeStyle = "#1376AF";
    App.ctx.lineWidth = 5;
    App.ctx.lineCap = "round";
    App.socket = io.connect('http://localhost:4000');
    App.socket.on('draw', function(data) {
      return App.draw(data.x, data.y, data.type);
    });
    App.draw = function(x, y, type) {
      if (type === "dragstart") {
        App.ctx.beginPath();
        return App.ctx.moveTo(x, y);
      } else if (type === "drag") {
        App.ctx.lineTo(x, y);
        return App.ctx.stroke();
      } else {
        return App.ctx.closePath();
      }
    };
  };


  /*
  	Draw Events
   */

  $(document).on('mousedown', 'canvas', function(e) {
    isDrawing = true;
    var x = e.offsetX;
    var y = e.offsetY;
    App.draw(x, y, 'dragstart');
    App.socket.emit('drawClick', { x: x, y: y, type: 'dragstart' });
  });

  $(document).on('mousemove', function(e) {
    if (!isDrawing) return;
    var offset = $(App.canvas).offset();
    var x = e.pageX - offset.left;
    var y = e.pageY - offset.top;
    App.draw(x, y, 'drag');
    App.socket.emit('drawClick', { x: x, y: y, type: 'drag' });
  });

  $(document).on('mouseup', function(e) {
    if (!isDrawing) return;
    isDrawing = false;
    var offset = $(App.canvas).offset();
    var x = e.pageX - offset.left;
    var y = e.pageY - offset.top;
    App.draw(x, y, 'dragend');
    App.socket.emit('drawClick', { x: x, y: y, type: 'dragend' });
  });

  $(function() {
    return App.init();
  });

}).call(this);
