// Generated by CoffeeScript 1.10.0 - Modified for Color/Size feature
(function() {
  var App;

  App = {};

  var isDrawing = false;

  // Brush settings
  App.brushColor = '#1376AF';
  App.brushSize = 5;

  /*
  	Init
   */

  App.init = function() {
    App.canvas = document.createElement('canvas');
    // Adjust canvas height to account for toolbar (60px)
    App.canvas.height = window.innerHeight - 60;
    App.canvas.width = window.innerWidth;
    document.getElementsByTagName('article')[0].appendChild(App.canvas);
    App.ctx = App.canvas.getContext("2d");
    App.ctx.fillStyle = "solid";
    App.ctx.strokeStyle = App.brushColor;
    App.ctx.lineWidth = App.brushSize;
    App.ctx.lineCap = "round";

    App.socket = io.connect('http://localhost:4000');

    // Listen for draw events from other users
    App.socket.on('draw', function(data) {
      return App.draw(data.x, data.y, data.type, data.color, data.lineWidth);
    });

    // Initialize toolbar
    App.initToolbar();
    App.updatePreview();
  };

  /*
  	Draw function - accepts color and lineWidth for remote strokes
   */
  App.draw = function(x, y, type, color, lineWidth) {
    // Save current context state
    var prevColor = App.ctx.strokeStyle;
    var prevLineWidth = App.ctx.lineWidth;

    // Use provided color/size or defaults
    var drawColor = color || App.brushColor;
    var drawLineWidth = lineWidth || App.brushSize;

    // Set the drawing styles
    App.ctx.strokeStyle = drawColor;
    App.ctx.lineWidth = drawLineWidth;

    if (type === "dragstart") {
      App.ctx.beginPath();
      App.ctx.moveTo(x, y);
    } else if (type === "drag") {
      App.ctx.lineTo(x, y);
      App.ctx.stroke();
    } else {
      App.ctx.closePath();
    }

    // Restore context to user's current brush settings
    App.ctx.strokeStyle = prevColor;
    App.ctx.lineWidth = prevLineWidth;
  };

  /*
  	Toolbar Initialization
   */
  App.initToolbar = function() {
    // Color picker event handlers
    $('.color-btn').on('click', function() {
      var color = $(this).data('color');
      App.setColor(color);

      // Update selection UI
      $('.color-btn').removeClass('selected');
      $(this).addClass('selected');
    });

    // Size preset buttons
    $('.size-btn').on('click', function() {
      var size = parseInt($(this).data('size'), 10);
      App.setSize(size);

      // Update selection UI
      $('.size-btn').removeClass('selected');
      $(this).addClass('selected');

      // Sync slider
      $('#size-slider').val(size);
      $('#size-value').text(size + 'px');
    });

    // Size slider
    $('#size-slider').on('input', function() {
      var size = parseInt($(this).val(), 10);
      App.setSize(size);
      $('#size-value').text(size + 'px');

      // Update preset button selection
      var presetSizes = [2, 5, 10, 20];
      $('.size-btn').removeClass('selected');
      if (presetSizes.indexOf(size) !== -1) {
        $('.size-btn[data-size="' + size + '"]').addClass('selected');
      }
    });
  };

  /*
  	Set color helper
   */
  App.setColor = function(color) {
    App.brushColor = color;
    App.ctx.strokeStyle = color;
    App.updatePreview();
  };

  /*
  	Set size helper
   */
  App.setSize = function(size) {
    App.brushSize = size;
    App.ctx.lineWidth = size;
    App.updatePreview();
  };

  /*
  	Update brush preview
   */
  App.updatePreview = function() {
    var previewDot = document.getElementById('preview-dot');
    if (previewDot) {
      previewDot.style.backgroundColor = App.brushColor;
      previewDot.style.width = Math.min(App.brushSize, 30) + 'px';
      previewDot.style.height = Math.min(App.brushSize, 30) + 'px';
    }
  };

  /*
  	Draw Events - includes color and size in socket emissions
   */

  $(document).on('mousedown', 'canvas', function(e) {
    isDrawing = true;
    var x = e.offsetX;
    var y = e.offsetY;
    App.draw(x, y, 'dragstart', App.brushColor, App.brushSize);
    App.socket.emit('drawClick', {
      x: x,
      y: y,
      type: 'dragstart',
      color: App.brushColor,
      lineWidth: App.brushSize
    });
  });

  $(document).on('mousemove', function(e) {
    if (!isDrawing) return;
    var offset = $(App.canvas).offset();
    var x = e.pageX - offset.left;
    var y = e.pageY - offset.top;
    App.draw(x, y, 'drag', App.brushColor, App.brushSize);
    App.socket.emit('drawClick', {
      x: x,
      y: y,
      type: 'drag',
      color: App.brushColor,
      lineWidth: App.brushSize
    });
  });

  $(document).on('mouseup', function(e) {
    if (!isDrawing) return;
    isDrawing = false;
    var offset = $(App.canvas).offset();
    var x = e.pageX - offset.left;
    var y = e.pageY - offset.top;
    App.draw(x, y, 'dragend', App.brushColor, App.brushSize);
    App.socket.emit('drawClick', {
      x: x,
      y: y,
      type: 'dragend',
      color: App.brushColor,
      lineWidth: App.brushSize
    });
  });

  /*
  	Handle window resize
   */
  $(window).on('resize', function() {
    App.canvas.width = window.innerWidth;
    App.canvas.height = window.innerHeight - 60;
    // Restore context settings after resize (canvas resize clears them)
    App.ctx.strokeStyle = App.brushColor;
    App.ctx.lineWidth = App.brushSize;
    App.ctx.lineCap = "round";
    App.ctx.fillStyle = "solid";
  });

  $(function() {
    return App.init();
  });

}).call(this);
