// Generated by CoffeeScript 1.10.0
(function() {
  var io;

  io = require('socket.io')(4000, {
    cors: {
      origin: "*",
      methods: ["GET", "POST"]
    }
  });

  io.sockets.on('connection', function(socket) {
    socket.on('drawClick', function(data) {
      socket.broadcast.emit('draw', {
        x: data.x,
        y: data.y,
        type: data.type,
        color: data.color || '#1376AF',
        lineWidth: data.lineWidth || 5
      });
    });
  });

}).call(this);
